import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';

import { IPlanet } from '../interfaces/inteface-planets';
import { ServicePlanet } from '../services/service-planet';
import { formatDate } from '../utils/format-date';
import { useWishlist } from '../provider/provider-store';

const Detail: NextPage = () => {
  const { wishlist, addWishlist } = useWishlist();
  const router: { query: { url?: string } } = useRouter();

  const [data, setData] = useState<IPlanet>({
    name: '',
    rotation_period: '',
    orbital_period: '',
    diameter: '',
    climate: '',
    gravity: '',
    terrain: '',
    surface_water: '',
    population: '',
    url: '',
    created: '',
    edited: ''
  });

  useEffect(() => {
    async function getDetail(url: string) {
      try {
        const response = await ServicePlanet.getDetail(url);
        setData(response.data);
      } catch (error) {}
    }

    if (router.query && router.query.url) {
      getDetail(router.query.url);
    }
  }, [router.query]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="bg-gray-800 py-4 mb-4">
        <div className="max-w-2xl mx-auto flex flex-row space-x-4 text-white items-center">
          <h1>Swapi.com</h1>
          <ul className="flex flex-row space-x-4">
            <li className="text-sm">Planets</li>
          </ul>
        </div>
      </nav>
      <main className="max-w-2xl mx-auto">
        <h1 className="text-3xl">{data.name}</h1>
        <div className="grid grid-cols-3 gap-6 mt-6">
          <div>
            <strong>Climate</strong>
            <p>{data.climate}</p>
          </div>
          <div>
            <strong>Diameter</strong>
            <p>{data.diameter}</p>
          </div>
          <div>
            <strong>Population</strong>
            <p>{data.population}</p>
          </div>
          <div>
            <strong>Orbital Period</strong>
            <p>{data.orbital_period}</p>
          </div>
          <div>
            <strong>Gravity</strong>
            <p>{data.gravity}</p>
          </div>
          <div>
            <strong>Surface Water</strong>
            <p>{data.surface_water}</p>
          </div>
          <div>
            <strong>Rotation Period</strong>
            <p>{data.rotation_period}</p>
          </div>
          <div>
            <strong>Terrain</strong>
            <p>{data.terrain}</p>
          </div>
          <div>
            <strong>Created Date</strong>
            <p>{data.created != '' ? formatDate(data.created) : ''}</p>
          </div>
        </div>
        <button
          className="mt-4 bg-green-600 text-sm py-2 px-4 rounded-sm text-white"
          onClick={() => addWishlist(data)}
        >
          Add To Wishlist
        </button>
      </main>
    </div>
  );
};

export default Detail;
