import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';
import { IPlanet, IRespPlanet } from 'interfaces/inteface-planets';
import { ServicePlanet } from 'services/service-planet';

const Home: NextPage = () => {
  const [data, setData] = useState<IRespPlanet>({
    count: 0,
    next: null,
    previous: null,
    results: []
  });

  useEffect(() => {
    async function getPlanets() {
      try {
        const response = await ServicePlanet.get();
        setData(response.data);
      } catch (error) {}
    }

    getPlanets();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="bg-gray-800 py-4 mb-4">
        <div className="max-w-2xl mx-auto flex flex-row space-x-4 text-white">
          <h1>Swapi.com</h1>
          <ul className="flex flex-row space-x-4">
            <li>Planets</li>
          </ul>
        </div>
      </nav>
      <main className="max-w-2xl mx-auto">
        <div className="grid grid-cols-3 gap-3 ">
          {data.results.map((val: IPlanet, key: number) => {
            return (
              <Link key={key} href={'/detail'}>
                <div className="border border-gray-800 p-6 rounded-md h-full">
                  <h3 className="text-xl font-bold">{val.name}</h3>
                  <strong>Climate</strong>
                  <p>{val.climate}</p>
                  <strong>Diameter</strong>
                  <p>{val.diameter}</p>
                  <strong>Gravity</strong>
                  <p>{val.gravity}</p>
                  <strong>Surface Water</strong>
                  <p>{val.surface_water}</p>
                  <strong>Terrain</strong>
                  <p>{val.terrain}</p>
                </div>
              </Link>
            );
          })}
        </div>
      </main>
    </div>
  );
};

export default Home;
