import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { IPlanet, IRespPlanet } from '../interfaces/inteface-planets';
import { ServicePlanet } from '../services/service-planet';
import CardPlanet from '../components/card-planet/card-planet';

const Home: NextPage = () => {
  const [loading, setLoading] = useState<boolean>(false);
  const [page, setPage] = useState<number>(1);
  const [data, setData] = useState<IRespPlanet>({
    count: 0,
    next: null,
    previous: null,
    results: []
  });

  async function getPlanets(page: number) {
    setLoading(true);
    try {
      const response = await ServicePlanet.get(page);
      let newPlanets = { ...data };
      newPlanets.next = response.data.next;
      newPlanets.count = response.data.count;
      newPlanets.results = [...newPlanets.results, ...response.data.results];
      setData(newPlanets);
      setLoading(false);
    } catch (error) {
      setLoading(false);
    }
  }

  useEffect(() => {
    getPlanets(page);
  }, []);

  useEffect(() => {
    const handleScroll = () => {
      if (
        window.innerHeight + document.documentElement.scrollTop >=
        document.documentElement.offsetHeight - 100
      ) {
        let limit = 10;
        let nextPage = page + 1;
        console.log(data.count);
        if (!loading && nextPage < Math.ceil(data.count / limit)) {
          setPage(nextPage);
          getPlanets(nextPage);
        }
      }
    };

    window.addEventListener('scroll', handleScroll);

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, [loading, page, data]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="bg-gray-800 py-4 mb-4">
        <div className="max-w-2xl mx-auto flex flex-row space-x-4 text-white">
          <h1>Swapi.com</h1>
          <ul className="flex flex-row space-x-4">
            <li>
              <Link href={'/'}>Planets</Link>
            </li>
            <li>
              <Link href={'/wishlist'}>Wishlist</Link>
            </li>
          </ul>
        </div>
      </nav>
      <main className="max-w-2xl mx-auto">
        <div className="grid grid-cols-3 gap-3 ">
          {data.results.map((val: IPlanet, key: number) => {
            return <CardPlanet planet={val} key={key} />;
          })}
        </div>
        {loading && <p>Loading...</p>}
      </main>
    </div>
  );
};

export default Home;
