import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { IPlanet } from '../interfaces/inteface-planets';
import { useWishlist } from '../provider/provider-store';
import CardPlanet from '../components/card-planet/card-planet';

const Wishlist: NextPage = () => {
  const { wishlist } = useWishlist();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="bg-gray-800 py-4 mb-4">
        <div className="max-w-2xl mx-auto flex flex-row space-x-4 text-white">
          <h1>Swapi.com</h1>
          <ul className="flex flex-row space-x-4">
            <li>
              <Link href={'/'}>Planets</Link>
            </li>
            <li>
              <Link href={'/wishlist'}>Wishlist</Link>
            </li>
          </ul>
        </div>
      </nav>
      <main className="max-w-2xl mx-auto">
        <div className="grid grid-cols-3 gap-3 ">
          {wishlist.map((val: IPlanet, key: number) => {
            return <CardPlanet planet={val} key={key} />;
          })}
        </div>
      </main>
    </div>
  );
};

export default Wishlist;
